### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by zivillian** [anszom/rethink#5]
I started a [similar project](https://github.com/zivillian/LGThinQ/) a few days ago and found your wiki and project after I was able to capture the communication between the app and appliance and started searching for `RTK_RTL8711am`.

I'm trying to "uncloud" my washing machine [F4WV709P1E.ABWQWDG](https://www.lg.com/de/waeschepflege/waschmaschinen/f4wv709p1e/).

I spend a few hours reading the wiki and I guess that we should combine our effort.

Right now I don't know what information you have that I don't know and also the other way around. I'm also not sure what of the things I've discovered are specific for my device.

Feel free to send me a direct mail - I'm sure you know how to do that ;-)

**Comment by anszom** [comment]
I'd be happy to extend `rethink` to support other devices. I've sent you an e-mail.
